accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('signup/',views.signup_view,name='signup')
]

blog/urls.py
from django.urls import path
from blog.views import *


app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('search/', blog_search, name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('robots.txt', include('robots.urls')),
    re_path(r'^password-reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password-reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^password-reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *


app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
]

website/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ["created_date"]

    def __str__(self):
        return self.name

website/forms.py
from django import forms
from website.models import Contact
from captcha.fields import CaptchaField


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        fields = ["name", "email", "subject", "message"]

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields["subject"].required = False

website/views.py
from django.shortcuts import render
from website.forms import ContactForm
from django.contrib import messages


def index_view(request):
    return render(request, "website/index.html")

def about_view(request):
    return render(request, "website/about.html")

def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.name = "Anonymous"
            contact.save()
            messages.add_message(request, messages.SUCCESS, 'Your ticket is submitted successfully.')
        else:
            messages.add_message(request, messages.ERROR, 'Your ticket is not submitted.')
    form = ContactForm()
    return render(request, "website/contact.html", {"form": form})

templates/website/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Page Header Start -->
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>About Us</h2>
                </div>
                <div class="col-12">
                    <a href="{% url 'website:index' %}">Home</a>
                    <a href="{% url 'website:about' %}">About Us</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- About Start -->
    <div class="about wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-5 col-md-6">
                    <div class="about-img">
                        <img src="{% static 'img/about.png' %}" alt="Image">
                    </div>
                </div>
                <div class="col-lg-7 col-md-6">
                    <div class="section-header text-left">
                        <p>Learn About Us</p>
                        <h2>Welcome to Yooga</h2>
                    </div>
                    <div class="about-text">
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida condimentum, viverra quis sem.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida condimentum, viverra quis sem. Curabitur non nisl nec nisi scelerisque maximus.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->


    <!-- Team Start -->
    <div class="team">
        <div class="container">
            <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                <p>Yoga Trainer</p>
                <h2>Expert Yoga Trainer</h2>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.0s">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{% static 'img/team-1.jpg' %}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Millie Harper</h2>
                            <p>Yoga Teacher</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{% static 'img/team-2.jpg' %}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Lilly Fry</h2>
                            <p>Yoga Teacher</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.4s">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{% static 'img/team-3.jpg' %}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Elise Moran</h2>
                            <p>Yoga Teacher</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{% static 'img/team-4.jpg' %}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Kate Glover</h2>
                            <p>Yoga Teacher</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Team End -->

{% endblock %}

templates/website/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Page Header Start -->
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Contact</h2>
                </div>
                <div class="col-12">
                    <a href="{% url 'website:index' %}">Home</a>
                    <a href="{% url 'website:contact' %}">Contact</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="contact">
        <div class="container">
            <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                <p>Get In Touch</p>
                <h2>For Any Query</h2>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="row">
                        <div class="col-md-4 contact-item wow zoomIn" data-wow-delay="0.2s">
                            <i class="fa fa-map-marker-alt"></i>
                            <div class="contact-text">
                                <h2>Location</h2>
                                <p>123 Street, New York, USA</p>
                            </div>
                        </div>
                        <div class="col-md-4 contact-item wow zoomIn" data-wow-delay="0.4s">
                            <i class="fa fa-phone-alt"></i>
                            <div class="contact-text">
                                <h2>Phone</h2>
                                <p>+012 345 67890</p>
                            </div>
                        </div>
                        <div class="col-md-4 contact-item wow zoomIn" data-wow-delay="0.6s">
                            <i class="far fa-envelope"></i>
                            <div class="contact-text">
                                <h2>Email</h2>
                                <p>info@example.com</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="contact-form">
                        <form name="sentMessage" id="contactForm" novalidate="novalidate" action="{% url 'website:contact' %}" method="post">
                            {% csrf_token %}
                            <div class="control-group">
                                <input name="name" placeholder="Your Name" class="form-control" type="text" required=""/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input name="email" placeholder="Your Email" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" class="form-control" type="email" required=""/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input name="subject" placeholder="Subject" class="form-control" type="text"/>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control" name="message" placeholder="Message" required="required" ></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div>
                                <div class="pb-3" >{{ form.captcha }}</div>
                                <div class="alert-msg" style="text-align: left;"></div>
                                <button type="submit" class="btn">Send Message</button>											
                            </div>
                        </form>

						
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-error">
                        <h4>Please fix the following errors</h4>
                        <ul>
                            {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                                {% endfor %}
                            {% endif %}
                            {% endfor %}
                        </ul>
                        {% if form.non_field_errors %}
                            {{ form.non_field_errors }}
                        {% endif %}
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

{% endblock %}

templates/website/index.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block content %}
    <!-- Hero Start -->
    <div class="hero">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-sm-12 col-md-6">
                    <div class="hero-text">
                        <h1>Yoga Practice For Good Health</h1>
                        <p>
                            Lorem ipsum dolor sit amet elit. Phasell nec pretum mi. Curabi ornare velit non. Aliqua metus tortor auctor quis sem.
                        </p>
                        <div class="hero-btn">
                            <a class="btn" href="{% url 'accounts:signup' %}">Join Now</a>
                            {% if request.user.is_authenticated %}
                            <a class="btn" href="{% url 'accounts:logout' %}">Logout</a>
                            {% else %}
                            <a class="btn" href="{% url 'accounts:login' %}">Login</a>
                            {% endif %}
                            
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6">
                    <div class="hero-image">
                        <img src="{% static 'img/hero.png' %}" alt="Hero Image">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- About Start -->
    <div class="about wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-5 col-md-6">
                    <div class="about-img">
                        <img src="{% static 'img/about.png' %}" alt="Image">
                    </div>
                </div>
                <div class="col-lg-7 col-md-6">
                    <div class="section-header text-left">
                        <p>Learn About Us</p>
                        <h2>Welcome to Yooga</h2>
                    </div>
                    <div class="about-text">
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida condimentum, viverra quis sem.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida condimentum, viverra quis sem. Curabitur non nisl nec nisi scelerisque maximus.
                        </p>
                        <a class="btn" href="{% url 'website:about' %}">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->


    <!-- Blog Start -->
    <div class="blog">
        <div class="container">
            <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                <p>From Blog</p>
                <h2>Latest Yoga Articles</h2>
            </div>
            
            <div class="owl-carousel blog-carousel wow fadeInUp" data-wow-delay="0.1s">

            {% posts as totalposts %}
            {% for post in totalposts %}
                <div class="blog-item">
                    <div class="blog-img">
                        <img src="{{ post.image.url }}" alt="{{ post.title }}">
                    </div>
                    <div class="blog-text">
                        <h2>{{ post.title }}</h2>
                        <div class="blog-meta">
                            <p><i class="far fa-list-alt"></i>{{ post.author }}</p>
                            <p><i class="far fa-calendar-alt"></i>{{ post.published_date|date:"d M Y" }}</p>
                            <p><i class="far fa-comments"></i>{{ post.counted_views }}</p>
                        </div>
                        <p>{{ post.content|truncatewords:20 }}</p>
                        <a class="btn" href="">Read More <i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            {% endfor %}

            </div>
        </div>
    </div>
    <!-- Blog End -->
{% endblock %}