blog/urls.py
from django.urls import path
from blog.views import *


app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('search/', blog_search, name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('robots.txt', include('robots.urls')),
    re_path(r'^password-reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password-reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^password-reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *


app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    image = models.ImageField(upload_to="blog/", default="blog/default.jpg")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return "{} - {}".format(self.title, self.id)

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid':self.id})

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["post" ,"name", "email", "subject", "message"]

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.utils import timezone
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from blog.forms import CommentForm

def blog_view(request, **kwargs):
    posts = Post.objects.filter(status=1, published_date__lte=timezone.now())
    if kwargs.get("cat_name"):
        posts = posts.filter(category__name=kwargs["cat_name"])
    if kwargs.get("author_username"):
        posts = posts.filter(author__username=kwargs["author_username"])
    if kwargs.get("tag_name"):
        posts = posts.filter(tags__name__in=[kwargs["tag_name"]])

    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get("page")
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    context = {"posts": posts}
    return render(request, "blog/blog.html", context)

def blog_single(request, pid):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your comment is submitted successfully.')
        else:
            messages.add_message(request, messages.ERROR, 'Your comment is not submitted.')

    posts = Post.objects.filter(status=1)
    post = get_object_or_404(posts, id=pid)
    post.counted_views= post.counted_views + 1
    post.save()

    # None if there's no previous
    previous_post = posts.filter(id__lt=post.id).order_by('-id').first()
    # None if there's no next
    next_post = posts.filter(id__gt=post.id).order_by('id').first()

    if not post.login_require:
        comments = Comment.objects.filter(post=post.id, approved=True)
        form = CommentForm()
        context = {"post": post, "comments":comments, "form":form, "previous_post":previous_post, "next_post":next_post}
        return render(request, "blog/single.html", context)
    else:
        return HttpResponseRedirect(reverse('accounts:login'))

def blog_search(request):
    posts = Post.objects.filter(status=1, published_date__lte=timezone.now())
    if request.method == "GET":
        if s := request.GET.get("s"):
            posts = posts.filter(content__contains=s)
    context = {"posts": posts}
    return render(request, "blog/blog.html", context)

def handler404(request, exception):
    return render(request, '404.html', status=404)

templates/blog/blog.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Page Header Start -->
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Yoga Blog</h2>
                </div>
                <div class="col-12">
                    <a href="">Home</a>
                    <a href="">Yoga Blog</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Blog Start -->
    <div class="blog">
        <div class="container">
            <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                <p>From Blog</p>
                <h2>Latest Yoga Articles</h2>
            </div>
            
            <div class="row blog-page">
                {% for post in posts %}
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.0s">
                    <div class="blog-item">
                        <div class="blog-img">
                            <img src="{{ post.image.url }}" alt="{{ post.title }}">
                        </div>
                        <div class="blog-text">
                            <h2>{{ post.title }}</h2>
                            <div class="blog-meta">
                                <p><i class="far fa-list-alt"></i>{{ post.author }}</p>
                                <p><i class="far fa-calendar-alt"></i>{{ post.published_date|date:"d M Y" }}</p>
                                <p><i class="far fa-comments"></i>{{ post.counted_views }}</p>
                            </div>
                            <p>
                                {{ post.content|truncatewords:20 }}
                            </p>
                            <a class="btn" href="{% url 'blog:single' pid=post.id %}">Read More <i class="fa fa-angle-right"></i></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            

            <div class="row">
                <div class="col-12">
                    <ul class="pagination justify-content-center">
                        {% if posts.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{posts.previous_page_number}}">Previous</a></li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        {% endif %}
                        {% for i in posts.paginator.page_range %}
                            {% if posts.number == i %}
                                <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                            {% else %}
                                <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if posts.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{posts.next_page_number}}">Next</a></li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        {% endif %}
                    </ul> 
                </div>
            </div>

        </div>
    </div>
    <!-- Blog End -->

{% endblock %}

templates/blog/categories.html
{% load blog_tags %}

<div class="sidebar-widget wow fadeInUp">
    <h2 class="widget-title">Categories</h2>
    <div class="category-widget">
        <ul>
        {% for name,count in categories.items %}
            <li>
                <a href="{% url 'blog:category' cat_name=name %}">{{name}}</a>
                <span>( {{count}} )</span>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>

templates/blog/latest-posts.html
{% load blog_tags %}
{% load humanize %}

<div class="sidebar-widget wow fadeInUp">
    <h2 class="widget-title">Recent Post</h2>
    <div class="recent-post">
    {% for post in posts %}
        <div class="post-item">
            <div class="post-img">
                <img src="{{post.image.url}}" alt="{{post.title}}"/>
            </div>
             <div class="post-text">
                <a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a>
                <div class="post-meta"><p>{{post.published_date}}</p></div>
            </div>
        </div>
    {% endfor %}															
    </div>
</div>

templates/blog/search.html
{% load static %}

<div class="sidebar-widget wow fadeInUp">
    <div class="search-widget">
        <form action="{% url 'blog:search' %}" method="get">
            <input class="form-control" type="text" name="s" placeholder="Search Keyword">
            <button class="btn"><i class="fa fa-search"></i></button>
        </form>
    </div>
</div>

templates/blog/single.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}

{% block content %}
    <!-- Page Header Start -->
    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>{{ post.title }}</h2>
                </div>
                <div class="col-12">
                    <a href="{% url 'website:index' %}">Home</a>
                    <a href="">{{ post.title }}</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Single Post Start-->
    <div class="single">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="single-content wow fadeInUp">
                        <img src="{{ post.image.url }}" alt="{{ post.title }}"/>
                        <h2>{{ post.title }}</h2>
                        <p>
                            {{ post.content|linebreaksbr }}
                        </p>
                    </div>
                    <div class="single-tags wow fadeInUp">
                        {% for cat in post.category.all %}
                            <a href="#">{{ cat.name }}</a>
                        {% endfor %}
                    </div>
                    <div class="single-bio wow fadeInUp">
                        <div class="single-bio-img">
                            <img src="{% static 'img/user.jpg' %}" />
                        </div>
                        <div class="single-bio-text">
                            <h3>Author: {{ post.author.username }}</h3>
                            <p>Email Address: {{ post.author.email }}</p>
                        </div>
                    </div>

                    <div class="single-comment wow fadeInUp">
                        <h2>{{ comments|length }} Comments</h2>
                        <ul class="comment-list">
                            {% for comment in comments %}
                            <li class="comment-item">
                                <div class="comment-body">
                                    <div class="comment-text">
                                        <h3><a href="">{{ comment.name }}</a></h3>
                                        <span>{{ comment.created_date|date:"d M Y" }}</span>
                                        <p>{{ comment.message }}</p>
                                        {% comment %} <a class="btn" href="">Reply</a> {% endcomment %}
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="comment-form wow fadeInUp">
                        <h2>Leave a comment</h2>
                        <form method="post" action="{% url 'blog:single' pid=post.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="post" value={{post.id}}>
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input type="text" class="form-control" name="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input type="email" class="form-control" name="email">
                            </div>
                            <div class="form-group">
                                <label for="subject">Subject *</label>
                                <input type="text" class="form-control" name="subject">
                            </div>
                            <div class="form-group">
                                <label for="message">Message *</label>
                                <textarea name="message" cols="30" rows="5" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn">
                            </div>
                        </form> 
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="sidebar">
                        
                        {% include 'blog/search.html' %}

                        {% latestposts %}

                        <div class="sidebar-widget wow fadeInUp">
                            <div class="image-widget">
                                <a href="#"><img src="{% static 'img/blog-1.jpg' %}" alt="Image"></a>
                            </div>
                        </div>

                        {% postcategories %}

                        <div class="sidebar-widget wow fadeInUp">
                            <div class="image-widget">
                                <a href="#"><img src="{% static 'img/blog-3.jpg' %}" alt="Image"></a>
                            </div>
                        </div>

                        <div class="sidebar-widget wow fadeInUp">
                            <h2 class="widget-title">Tags Cloud</h2>
                            <div class="tag-widget">
                                {% for tag in post.tags.all %}
                                <a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Single Post End-->   

{% endblock %}